### PR TITLE
Add conditional parsing of request params

### PR DESCRIPTION
**Pull request by ghost**
Access params values by index when params contains list with object

### CODE REVIEW

**Comment by shawnshaddock** [comment]
Thanks for the pull request. Is this to support request parameters by-position through an Array as per the spec? https://www.jsonrpc.org/specification#parameter_structures

**Comment by ghost** [comment]
Yes.

**Comment by shawnshaddock** [comment]
Awesome, thanks for the contribution!

**Comment by shawnshaddock** [comment]
Do you need a nuget build with this fix?

**Comment by ghost** [comment]
No. Thank you.

**Pull request merged**
